### ISSUE TITLE
'folly/experimental/coro/Coroutine.h' file not found after upgrading to > RN 0.74

### ISSUE THREAD

**Issue by MrShakes** [facebook/folly#2297]
Currently upgrading to RN 0.75.2 from 0.73.x and encountered the error below on IOS, downgraded to RN 0.74.5 and had the same issue.
Extensive research online seems to indicate that "folly/experimental" is deprecated and should no longer be available however it's still being called somewhere. Not completely sure if this is the issue though.
Uninstalling/removing RNBranch still gives the same error

Xcode version 15.3
Pod version  1.15.2
ruby 3.2.1 (2023-02-08 revision 31819e82c8) [arm64-darwin22]
```
❌  /Users/[REDACTED]/Library/Developer/Xcode/DerivedData/Oreille-bxxuvxrzbbojtictzbxfgyypfvxf/Build/Intermediates.noindex/ArchiveIntermediates/Oreille/BuildProductsPath/Release-iphoneos/RCT-Folly/folly.framework/Headers/folly/Optional.h:667:10: 'folly/experimental/coro/Coroutine.h' file not found
#include <folly/experimental/coro/Coroutine.h>
                                                           ^
❌  /Users/[REDACTED]/Library/Developer/Xcode/DerivedData/Oreille-bxxuvxrzbbojtictzbxfgyypfvxf/Build/Intermediates.noindex/ArchiveIntermediates/Oreille/BuildProductsPath/Release-iphoneos/RCT-Folly/folly.framework/Headers/folly/Optional.h:667:10: 'folly/experimental/coro/Coroutine.h' file not found
#include <folly/experimental/coro/Coroutine.h>
         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
❌  /Users/[REDACTED]/Library/Developer/Xcode/DerivedData/Oreille-bxxuvxrzbbojtictzbxfgyypfvxf/Build/Intermediates.noindex/ArchiveIntermediates/Oreille/BuildProductsPath/Release-iphoneos/React-RCTAppDelegate/React_RCTAppDelegate.framework/Headers/RCTAppDelegate.h:8:9: could not build module 'React'
#import <React/RCTBridgeDelegate.h>
         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
❌  /Users/[REDACTED]/Library/Developer/Xcode/DerivedData/Oreille-bxxuvxrzbbojtictzbxfgyypfvxf/Build/Intermediates.noindex/ArchiveIntermediates/Oreille/BuildProductsPath/Release-iphoneos/react-native-branch/RNBranch.framework/Headers/RNBranch.h:2:9: could not build module 'React'
#import <React/RCTBridgeModule.h>
 ~~~~~~~^
 
 The following build commands failed:
	CompileC /Users/[REDACTED]/Library/Developer/Xcode/DerivedData/Oreille-bxxuvxrzbbojtictzbxfgyypfvxf/Build/Intermediates.noindex/ArchiveIntermediates/Oreille/IntermediateBuildFilesPath/Oreille.build/Release-iphoneos/Oreille.build/Objects-normal/arm64/AppDelegate.o /Users/[REDACTED]/git/ios/Oreille/AppDelegate.mm normal arm64 objective-c++ com.apple.compilers.llvm.clang.1_0.compiler (in target 'Oreille' from project 'Oreille')
(1 failure)
```

**Comment by MrShakes** [comment]
Adding `"-DFOLLY_CFG_NO_COROUTINES=1"` to pbxproj solved the issue

**Comment by santi020k** [comment]
Example how should be:
https://github.com/facebook/react-native/blob/ad341e39695d0e5ad3748f8fbb0ce51e58ade83d/packages/rn-tester/RNTesterPods.xcodeproj/project.pbxproj#L1041

**Comment by MrShakes** [comment]
Be sure to add all instances of `COROUTINES` as shown here, clean and try again https://github.com/facebook/react-native/blob/ad341e39695d0e5ad3748f8fbb0ce51e58ade83d/packages/rn-tester/RNTesterPods.xcodeproj/project.pbxproj

**Comment by nezort11** [comment]
yes, i have added "-DFOLLY_CFG_NO_COROUTINES=1" two times in debug and release

**Comment by nezort11** [comment]
I'have managed to solve this error coming from Optional.h header in RCT-Folly:

- XCode 15.3
- ruby 2.7.5p203
- pod 1.15.2
- react native 0.72.13

## Problem

```
/Users/<user>/dev/walnuts/ios/Pods/Headers/Public/RCT-Folly/folly/Optional.h:614:10
'folly/experimental/coro/Coroutine.h'
file not found
```
because of this code with import
`./ios/Pods/Headers/Public/RCT-Folly/folly/Optional.h`

<img width="993" alt="image" src="https://github.com/user-attachments/assets/6317f6c3-76f0-4881-88db-fe4aef2ca03b">


because `FOLLY_HAS_COROUTINES` is `1` and there is no `experimental` directory in `folly`

## Solution

Hardcode `FOLLY_HAS_COROUTINES` to define always to `0` (line 549)

```
open ./ios/Pods/RCT-Folly/folly/Portability.h
open ./ios/Pods/Flipper-Folly/folly/Portability.h
```

<img width="1055" alt="image" src="https://github.com/user-attachments/assets/9d92ec0e-1ebb-441c-9170-d1d679463edb">


And also comment some not important assertion:
```
open ./ios/Pods/Headers/Public/Flipper-Folly/folly/concurrency/CacheLocality.h
```

<img width="1159" alt="image" src="https://github.com/user-attachments/assets/ff1c2bfd-d200-4efa-acd6-3569d57f51c3">

**Comment by dylanmaryk** [comment]
Thanks @nezort11, your solution looks correct but I'm struggling to overwrite the value of `FOLLY_HAS_COROUTINES` when building the project on CI. Nothing is working so far. I don't have this issue locally, only on CI.

**Comment by dylanmaryk** [comment]
Adding this to the `Podfile` works for me, as a way to automate the fix on CI:

```
post_install do |installer|
    system("chmod -R u+w Pods/RCT-Folly")
    Dir.glob("Pods/RCT-Folly/folly/Portability.h").each do |file|
      text = File.read(file)
      new_contents = text.gsub('#define FOLLY_HAS_COROUTINES 1', '#define FOLLY_HAS_COROUTINES 0')
      File.open(file, "w") { |file| file.puts new_contents }
    end
  end
```

**Comment by johhansantana** [comment]
hey @dylanmaryk I've implemented the Podfile post_install script and it works locally but when using xcode cloud for example it fails with the `'folly/experimental/coro/Coroutine.h' file not found` error.

`/Volumes/workspace/repository/ios/Pods/Headers/Public/RCT-Folly/folly/Optional.h:614:10: fatal error: 'folly/experimental/coro/Coroutine.h' file not found
#include <folly/experimental/coro/Coroutine.h>`

This only happens on the CI/CD part. Do you have any clue on what could it be?

**Comment by p29hieu** [comment]
> hey @dylanmaryk I've implemented the Podfile post_install script and it works locally but when using xcode cloud for example it fails with the `'folly/experimental/coro/Coroutine.h' file not found` error.
> 
> `/Volumes/workspace/repository/ios/Pods/Headers/Public/RCT-Folly/folly/Optional.h:614:10: fatal error: 'folly/experimental/coro/Coroutine.h' file not found #include <folly/experimental/coro/Coroutine.h>`
> 
> This only happens on the CI/CD part. Do you have any clue on what could it be?

I got same issue.  This only happens on CI/CD. I'm using CircleCI. This is my resource
```    
macos:
    xcode: 15.0.0
resource_class: macos.m1.medium.gen1
```

**Comment by johhansantana** [comment]
@p29hieu @dylanmaryk I may have fixed it by updating the post_install script

```
# Modify RCT-Folly Portability.h to disable coroutines
Dir.glob(installer.sandbox.root + "RCT-Folly/folly/Portability.h") do |file|
  begin
    # First try to make the file writable
    system "chmod +w #{file}"
    
    contents = File.read(file)
    modified_contents = contents.gsub(/#define FOLLY_HAS_COROUTINES 1/, '#define FOLLY_HAS_COROUTINES 0')
    
    # Try writing with elevated privileges if needed
    if !File.writable?(file)
      system "sudo chmod +w #{file}"
    end
    
    File.write(file, modified_contents)
    
    # Optionally restore original permissions
    system "chmod -w #{file}"
  rescue => e
    Pod::UI.warn "Failed to modify Portability.h: #{e.message}"
  end
end
```

**Comment by iainbeeston** [comment]
Upgrading to react native 0.77 fixes this for me.

0.77 updates RCT-Folly from 2024.01.01.00 to 2024.11.18.00 ([here](https://github.com/facebook/react-native/compare/v0.76.5...v0.77.0-rc.0#diff-0fa072633240bad7dfa87e58e579132031948c37fbf8bf79de03f2ae83384fd5) is the diff). Version 2024.11.18.00 has the missing `folly/experimental/coro/Coroutine.h` file.

**Comment by abejfehr** [comment]
I upgraded to React Native 0.77 but I still get a similar issue when trying to integrate Expo with my RN app:

![Image](https://github.com/user-attachments/assets/0be1ac1d-bb0f-40bc-b747-e28507589bf6)

I've confirmed in my `Podfile.lock` that I'm on `2024.11.18.00`, at least that version is present in a lot of places as a dependency like:
```
    - RCT-Folly (= 2024.11.18.00)
```

My `ios/Pods/folly` directory does not contain a `coro` folder.

**Comment by hend-elsahli** [comment]
Pumping `react-native-gesture-handler`, and `react-native-screens` versions fixed the issue for me

**Comment by ts-sravan** [comment]
> I upgraded to React Native 0.77 which builds fine normally, but when trying to integrate the Expo SDK with my RN app I get this:
> 
> ![Image](https://github.com/user-attachments/assets/0be1ac1d-bb0f-40bc-b747-e28507589bf6)
> 
> I've confirmed in my `Podfile.lock` that I'm on `2024.11.18.00`, at least that version is present in a lot of places as a dependency like:
> 
> ```
>     - RCT-Folly (= 2024.11.18.00)
> ```
> 
> My `ios/Pods/folly` directory does not contain a `coro` folder.
> 
> I also just created a brand new RN project with:
> 
> ```
> npx @react-native-community/cli@latest init RNTest
> ```
> 
> that definitely uses RN 77, and installed cocoapods there, but there is _also_ neither a `experimental` folder nor a `coro` folder:
> 
> ```
> ~/Development/RNTest 🦄 ls ios/Pods/RCT-Folly/folly
> AtomicHashArray-inl.h		DynamicConverter.h		Indestructible.h		Range.h				Uri.h
> AtomicHashArray.h		Exception.h			IndexedMemPool.h		Replaceable.h			Utility.h
> AtomicHashMap-inl.h		ExceptionString.h		IntrusiveList.h			ScopeGuard.cpp			Varint.h
> AtomicHashMap.h			ExceptionWrapper-inl.h		Lazy.h				ScopeGuard.h			VirtualExecutor.h
> AtomicIntrusiveLinkedList.h	ExceptionWrapper.h		Likely.h			SharedMutex.cpp			algorithm
> AtomicLinkedList.h		Executor.h			MPMCPipeline.h			SharedMutex.h			base64.h
> AtomicUnorderedMap.h		Expected.h			MPMCQueue.h			Singleton-inl.h			chrono
> Benchmark.h			FBString.h			MacAddress.h			Singleton.h			concurrency
> BenchmarkUtil.h			FBVector.h			MapUtil.h			SingletonThreadLocal.h		container
> Bits.h				File.h				Math.h				SocketAddress.h			detail
> CPortability.h			FileUtil.cpp			MaybeManagedPtr.h		SpinLock.h			dynamic-inl.h
> CancellationToken-inl.h		FileUtil.h			Memory.h			String-inl.h			dynamic.h
> CancellationToken.h		Fingerprint.h			MicroLock.h			String.cpp			functional
> Chrono.h			FixedString.h			MicroSpinLock.h			String.h			hash
> ClockGettimeWrappers.h		FollyMemcpy.h			MoveWrapper.h			Subprocess.h			json
> ConcurrentBitSet.h		FollyMemset.h			ObserverContainer.h		Synchronized.h			json.h
> ConcurrentLazy.h		Format-inl.h			Optional.h			SynchronizedPtr.h		json_patch.h
> ConcurrentSkipList-inl.h	Format.cpp			Overload.h			ThreadCachedInt.h		json_pointer.h
> ConcurrentSkipList.h		Format.h			PackedSyncPtr.h			ThreadLocal.h			lang
> ConstexprMath.h			FormatArg.h			Padded.h			TimeoutQueue.h			memory
> ConstructorCallbackList.h	FormatTraits.h			Poly-inl.h			TokenBucket.h			net
> Conv.cpp			Function.h			Poly.h				Traits.h			observer
> Conv.h				GLog.h				PolyException.h			Try-inl.h			poly
> CppAttributes.h			GroupVarint.h			Portability.h			Try.h				portability
> CpuId.h				Hash.h				Preprocessor.h			UTF8String.h			small_vector.h
> DefaultKeepAliveExecutor.h	IPAddress.h			ProducerConsumerQueue.h		Unicode.cpp			sorted_vector_types.h
> Demangle.cpp			IPAddressException.h		RWSpinLock.h			Unicode.h			stop_watch.h
> Demangle.h			IPAddressV4.h			Random-inl.h			Unit.h				synchronization
> DiscriminatedPtr.h		IPAddressV6.h			Random.h			Uri-inl.h			system
> ```
> 
> but there are files that reference that 🤔
> 
> ```
> ~/Development/RNTest 🦄 cat ./ios/Pods/RCT-Folly/folly/Expected.h | grep /coro/
> #include <folly/coro/Coroutine.h>
> ```
> 
> how is that supposed to work? I see [the file present in the source for that tag](https://github.com/facebook/folly/tree/v2024.11.18.00/folly/coro), but it doesn't seem to be in my system
> 
> **Edit:** I've restored the Podfile patch to set `FOLLY_HAS_COROUTINES 0` in `Portability.h`, that builds successfully.

Tried still same issue  #include <folly/coro/Coroutine.h> file not found

**Comment by ts-sravan** [comment]
> Pumping `react-native-gesture-handler`, and `react-native-screens` versions fixed the issue for me

still same issue

**Comment by zeeklog** [comment]
When i build with EAS ,  The same ERROR:
```bash
Waiting for build to complete. You can press Ctrl+C to exit.
✖ Build failed

🍏 iOS build failed:
The "Run fastlane" step failed because of an error in the Xcode build process. We automatically detected following errors in your Xcode build logs:
- 'folly/experimental/coro/Coroutine.h' file not found
Refer to "Xcode Logs" below for additional, more detailed logs.

```

**Comment by eliezra236** [comment]
Update to Expo 54, I am getting this issue after installing nativewind, even uninstalling it, clearing expo, ios and android don't fix it.

**Comment by Woods-Jack** [comment]
> Update to Expo 54, I am getting this issue after installing nativewind, even uninstalling it, clearing expo, ios and android don't fix it.

`npx expo install --fix` suggested an updated version of `react-native-reanimated` and fixed this for me :)

**Comment by sampie777** [comment]
I managed to fix this without implementing a work around in the Podfile. I discovered React Native sets this COROUTINES command in the project file by adding the flag ```"-DFOLLY_CFG_NO_COROUTINES=1"``` in two places in the file. If you search for e.g. ```DFOLLY_MOBILE``` you'll find the two places that look similar to the screenshot.

_ios/hymnbook2.xcodeproj/project.pbxproj_

<img width="475" height="209" alt="Image" src="https://github.com/user-attachments/assets/c20e9004-8d49-4010-affb-c7f0195a8282" />

**Comment by ArindamRayMukherjee** [comment]
> I managed to fix this without implementing a work around in the Podfile. I discovered React Native sets this COROUTINES command in the project file by adding the flag `"-DFOLLY_HAVE_CLOCK_GETTIME=1"` in two places in the file. If you search for e.g. `DFOLLY_MOBILE` you'll find the two places that look similar to the screenshot.
> 

This works for me, sans the typo :) ... -DFOLLY_CFG_NO_COROUTINES=1

**Comment by hemanthc438** [comment]
I got the above error because of misamatch of react-native-reanimated in my react native expo app.
upgrading the library to the latest version solved it.

**Comment by marra-smartfit** [comment]
> > Update to Expo 54, I am getting this issue after installing nativewind, even uninstalling it, clearing expo, ios and android don't fix it.
> 
> `npx expo install --fix` suggested an updated version of `react-native-reanimated` and fixed this for me :)

October 2025, this helped me!
```
npx expo install --fix  
The following packages should be updated for best compatibility with the installed expo version:
  expo@54.0.18 - expected version: 54.0.19
  react-native-reanimated@3.17.5 - expected version: ~4.1.1
  react-native-safe-area-context@5.4.0 - expected version: ~5.6.0
Your project may not work correctly until you install the expected versions of the packages.
```

**Comment by abdelbarimessah** [comment]
> > Update to Expo 54, I am getting this issue after installing nativewind, even uninstalling it, clearing expo, ios and android don't fix it.
> 
> `npx expo install --fix` suggested an updated version of `react-native-reanimated` and fixed this for me :)
this work for me in nov 2025, i get some problem in the version of   react-native-reanimated@3.17.5 - expected version: ~4.1.1
  react-native-safe-area-context@5.4.0 - expected version: ~5.6.0 , thank you so much

**Comment by hsource** [comment]
In our case, we found that this is a problem with dependencies (in the Pods project) not having the same `-DFOLLY_CFG_NO_COROUTINES=1` flag as project.pbxproj

We added the following to fix this:

```
  post_install do |installer|
    # Add after all other code

    # Avoid `mobile/ios/Pods/Headers/Public/RCT-Folly/folly/Expected.h:1587:10:
    # 'folly/coro/Coroutine.h' file not found"`
    #
    # This flag is copied from the the project.pbxproj for the main project, but
    # we also need it for the Pods project since Expo imports Folly too.
    installer.pods_project.build_configurations.each do |config|
      config.build_settings['OTHER_CPLUSPLUSFLAGS'] ||= ['$(OTHER_CFLAGS)']
      config.build_settings['OTHER_CPLUSPLUSFLAGS'] << '-DFOLLY_CFG_NO_COROUTINES=1'
    end
  end
```

**Comment by gentlee** [comment]
Why does it happen only on CI?

**Comment by gentlee** [comment]
Fixed by adding this to the beginning of Podfile:

```ruby
# Disable New Architecture
ENV['RCT_NEW_ARCH_ENABLED'] = '0'
```

**Description**
Locally we installed pods with providing `RCT_NEW_ARCH_ENABLED=0` through the script, while on CI it wasn't disabled. And in RN 76 it is enabled by default.

**Comment by MatWaligora** [comment]
> Example how should be added: https://github.com/facebook/react-native/blob/ad341e39695d0e5ad3748f8fbb0ce51e58ade83d/packages/rn-tester/RNTesterPods.xcodeproj/project.pbxproj#L1041

This fixed it for me, and it automatically added these lines to my Podfile

within post_install
```
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        ...your_other_changes
        config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] ||= ['$(inherited)']
        config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] << 'FOLLY_CFG_NO_COROUTINES=1'
```
